#Configurations for material Chrysoprase.
[general]
	#The module blacklist of this material. "*" is an alias for all modules. If a module name occurs an odd number of times (including wildcards), then the module is blacklisted.
	moduleBlacklist = []
	#The alternative names of this material.
	alternativeNames = []
	#The color of this material.
	color = 5817680
	#The byproducts of this material.
	extras = []
	#The model type of the material.
	modelType = "crystal"
	#Should items of this material have the enchanted glow.
	hasEffect = false
	#Is the storage block of this material small (2x2).
	isSmallStorageBlock = false
[molten]
	#The temperature of this molten fluid.
	temperature = 1000
[mysticalagriculture]
	#The amount of material obtained by crafting Mystical Agriculture essence.
	outputCount = 4
	#The crop tier of this material.
	tier = 3
	#The amount of Mystical Agriculture essence required to craft materials.
	inputCount = 8
[exnihilocreatio]
	#The default base to sieve in Ex Nihilo Creatio to get this material.
	oreBase = "#gravel"
[exnihilosequentia]
	#The output chance of the sieve recipes added using an iron mesh.
	sieveIronChance = 0.008
	#The output chance of the sieve recipes added using a diamond mesh.
	sieveDiamondChance = 0.016
[mekanism]
	#The default base to use in Mekanism's Combiner to recreate ores.
	oreBase = "minecraft:cobblestone"
[thermalexpansion_mysticalagriculture]
	#The base seed output chance when growing Mystical Agriculture seeds in Thermal Expansion's Insolator with Phyto-Gro.
	basicChance = 100
	#The base seed output chance when growing Mystical Agriculture seeds in Thermal Expansion's Insolator with Rich Phyto-Gro.
	richChance = 105
	#The base seed output chance when growing Mystical Agriculture seeds in Thermal Expansion's Insolator with Fluxed Phyto-Gro.
	fluxChance = 110
