#Configurations for material Mithril.
[general]
	#The module blacklist of this material. "*" is an alias for all modules. If a module name occurs an odd number of times (including wildcards), then the module is blacklisted.
	moduleBlacklist = []
	#The alternative names of this material.
	alternativeNames = []
	#The color of this material.
	color = 5998511
	#The byproducts of this material.
	extras = []
	#The model type of the material.
	modelType = "metallic"
	#Should items of this material have the enchanted glow.
	hasEffect = false
	#Is the storage block of this material small (2x2).
	isSmallStorageBlock = false
[molten]
	#The temperature of this molten fluid.
	temperature = 1000
[exnihilocreatio]
	#The output chance of the sieve recipes added using an iron mesh.
	sieveIronChance = 0.075
	#The output chance of the sieve recipes added using a flint mesh.
	sieveFlintChance = 0.05
	#The default base to sieve in Ex Nihilo Creatio to get ore pieces.
	oreBase = "#crushedAndesite"
	#The output chance of the sieve recipes added using a diamond mesh.
	sieveDiamondChance = 0.15
