print("--- loading exnihilo.zs ---");

//End Cake Remove
recipes.remove(<exnihilocreatio:block_end_cake>);
mods.jei.JEI.removeAndHide(<exnihilocreatio:block_end_cake>);

//Ore Piece Oredict
<ore:pieceUranium>.remove(<exnihilocreatio:item_ore_yellorium:0>);
<ore:oreUranium>.remove(<exnihilocreatio:item_ore_yellorium:1>);

mods.exnihilocreatio.Sieve.removeAll();

//dirt
mods.exnihilocreatio.Sieve.addStringMeshRecipe(<ore:dirt>, <exnihilocreatio:item_pebble:0>, 1.0);
mods.exnihilocreatio.Sieve.addStringMeshRecipe(<ore:dirt>, <exnihilocreatio:item_pebble:0>, 1.0);
mods.exnihilocreatio.Sieve.addStringMeshRecipe(<ore:dirt>, <exnihilocreatio:item_pebble:0>, 0.5);
mods.exnihilocreatio.Sieve.addStringMeshRecipe(<ore:dirt>, <exnihilocreatio:item_pebble:0>, 0.5);
mods.exnihilocreatio.Sieve.addStringMeshRecipe(<ore:dirt>, <exnihilocreatio:item_pebble:0>, 0.1);
mods.exnihilocreatio.Sieve.addStringMeshRecipe(<ore:dirt>, <exnihilocreatio:item_pebble:0>, 0.1);
mods.exnihilocreatio.Sieve.addStringMeshRecipe(<ore:dirt>, <exnihilocreatio:item_pebble:1>, 0.5);
mods.exnihilocreatio.Sieve.addStringMeshRecipe(<ore:dirt>, <exnihilocreatio:item_pebble:1>, 0.1);
mods.exnihilocreatio.Sieve.addStringMeshRecipe(<ore:dirt>, <exnihilocreatio:item_pebble:2>, 0.5);
mods.exnihilocreatio.Sieve.addStringMeshRecipe(<ore:dirt>, <exnihilocreatio:item_pebble:2>, 0.1);
mods.exnihilocreatio.Sieve.addStringMeshRecipe(<ore:dirt>, <exnihilocreatio:item_pebble:3>, 0.5);
mods.exnihilocreatio.Sieve.addStringMeshRecipe(<ore:dirt>, <exnihilocreatio:item_pebble:3>, 0.1);
mods.exnihilocreatio.Sieve.addStringMeshRecipe(<ore:dirt>, <minecraft:wheat_seeds>, 0.7);
mods.exnihilocreatio.Sieve.addStringMeshRecipe(<ore:dirt>, <minecraft:melon_seeds>, 0.35);
mods.exnihilocreatio.Sieve.addStringMeshRecipe(<ore:dirt>, <minecraft:pumpkin_seeds>, 0.35);
mods.exnihilocreatio.Sieve.addStringMeshRecipe(<ore:dirt>, <exnihilocreatio:item_material:3>, 0.05);
mods.exnihilocreatio.Sieve.addStringMeshRecipe(<ore:dirt>, <exnihilocreatio:item_material:4>, 0.05);
mods.exnihilocreatio.Sieve.addStringMeshRecipe(<ore:dirt>, <exnihilocreatio:item_seed_oak>, 0.05);
mods.exnihilocreatio.Sieve.addStringMeshRecipe(<ore:dirt>, <exnihilocreatio:item_seed_spruce>, 0.05);
mods.exnihilocreatio.Sieve.addStringMeshRecipe(<ore:dirt>, <exnihilocreatio:item_seed_birch>, 0.05);
mods.exnihilocreatio.Sieve.addStringMeshRecipe(<ore:dirt>, <exnihilocreatio:item_seed_jungle>, 0.05);
mods.exnihilocreatio.Sieve.addStringMeshRecipe(<ore:dirt>, <exnihilocreatio:item_seed_acacia>, 0.05);
mods.exnihilocreatio.Sieve.addStringMeshRecipe(<ore:dirt>, <exnihilocreatio:item_seed_darkoak>, 0.05);
mods.exnihilocreatio.Sieve.addStringMeshRecipe(<ore:dirt>, <exnihilocreatio:item_seed_cactus>, 0.05);
mods.exnihilocreatio.Sieve.addStringMeshRecipe(<ore:dirt>, <exnihilocreatio:item_seed_sugarcane>, 0.05);
mods.exnihilocreatio.Sieve.addStringMeshRecipe(<ore:dirt>, <exnihilocreatio:item_seed_carrot>, 0.05);
mods.exnihilocreatio.Sieve.addStringMeshRecipe(<ore:dirt>, <exnihilocreatio:item_seed_potato>, 0.05);
mods.exnihilocreatio.Sieve.addStringMeshRecipe(<ore:dirt>, <exnihilocreatio:item_seed_rubber>, 0.05);
//Gravel
mods.exnihilocreatio.Sieve.addStringMeshRecipe(<ore:gravel>, <minecraft:flint>, 0.25);
mods.exnihilocreatio.Sieve.addFlintMeshRecipe(<ore:gravel>, <minecraft:flint>, 0.25);
mods.exnihilocreatio.Sieve.addFlintMeshRecipe(<ore:gravel>, <minecraft:coal:0>, 0.125);
mods.exnihilocreatio.Sieve.addFlintMeshRecipe(<ore:gravel>, <exnihilocreatio:item_ore_gold:0>, 0.05);
mods.exnihilocreatio.Sieve.addFlintMeshRecipe(<ore:gravel>, <exnihilocreatio:item_ore_iron:0>, 0.1);
mods.exnihilocreatio.Sieve.addFlintMeshRecipe(<ore:gravel>, <exnihilocreatio:item_ore_copper:0>, 0.05);
mods.exnihilocreatio.Sieve.addFlintMeshRecipe(<ore:gravel>, <exnihilocreatio:item_ore_lead:0>, 0.05);
mods.exnihilocreatio.Sieve.addFlintMeshRecipe(<ore:gravel>, <exnihilocreatio:item_ore_nickel:0>, 0.05);
mods.exnihilocreatio.Sieve.addFlintMeshRecipe(<ore:gravel>, <exnihilocreatio:item_ore_platinum:0>, 0.02);
mods.exnihilocreatio.Sieve.addFlintMeshRecipe(<ore:gravel>, <exnihilocreatio:item_ore_yellorium>, 0.05);
mods.exnihilocreatio.Sieve.addIronMeshRecipe(<ore:gravel>, <minecraft:dye:4>, 0.10);
mods.exnihilocreatio.Sieve.addIronMeshRecipe(<ore:gravel>, <minecraft:diamond>, 0.008);
mods.exnihilocreatio.Sieve.addIronMeshRecipe(<ore:gravel>, <minecraft:emerald>, 0.008);
mods.exnihilocreatio.Sieve.addIronMeshRecipe(<ore:gravel>, <exnihilocreatio:item_ore_gold:0>, 0.075);
mods.exnihilocreatio.Sieve.addIronMeshRecipe(<ore:gravel>, <exnihilocreatio:item_ore_iron:0>, 0.15);
mods.exnihilocreatio.Sieve.addIronMeshRecipe(<ore:gravel>, <exnihilocreatio:item_ore_copper:0>, 0.10);
mods.exnihilocreatio.Sieve.addIronMeshRecipe(<ore:gravel>, <exnihilocreatio:item_ore_lead:0>, 0.075);
mods.exnihilocreatio.Sieve.addIronMeshRecipe(<ore:gravel>, <exnihilocreatio:item_ore_nickel:0>, 0.075);
mods.exnihilocreatio.Sieve.addIronMeshRecipe(<ore:gravel>, <exnihilocreatio:item_ore_tungsten:0>, 0.075);
mods.exnihilocreatio.Sieve.addIronMeshRecipe(<ore:gravel>, <exnihilocreatio:item_ore_uranium:0>, 0.05);
mods.exnihilocreatio.Sieve.addIronMeshRecipe(<ore:gravel>, <exnihilocreatio:item_ore_osmium:0>, 0.05);
mods.exnihilocreatio.Sieve.addIronMeshRecipe(<ore:gravel>, <exnihilocreatio:item_ore_platinum:0>, 0.04);
mods.exnihilocreatio.Sieve.addIronMeshRecipe(<ore:gravel>, <exnihilocreatio:item_ore_boron>, 0.2);
mods.exnihilocreatio.Sieve.addIronMeshRecipe(<ore:gravel>, <exnihilocreatio:item_ore_lithium>, 0.2);
mods.exnihilocreatio.Sieve.addIronMeshRecipe(<ore:gravel>, <exnihilocreatio:item_ore_magnesium>, 0.2);
mods.exnihilocreatio.Sieve.addIronMeshRecipe(<ore:gravel>, <exnihilocreatio:item_ore_mithril>, 0.2);
mods.exnihilocreatio.Sieve.addIronMeshRecipe(<ore:gravel>, <exnihilocreatio:item_ore_thorium>, 0.2);
mods.exnihilocreatio.Sieve.addIronMeshRecipe(<ore:gravel>, <exnihilocreatio:item_ore_titanium>, 0.2);
mods.exnihilocreatio.Sieve.addIronMeshRecipe(<ore:gravel>, <exnihilocreatio:item_ore_yellorium>, 0.2);
mods.exnihilocreatio.Sieve.addIronMeshRecipe(<ore:gravel>, <thaumcraft:amber>, 0.008);
mods.exnihilocreatio.Sieve.addIronMeshRecipe(<ore:gravel>, <biomesoplenty:gem:0>, 0.008);
mods.exnihilocreatio.Sieve.addIronMeshRecipe(<ore:gravel>, <forestry:apatite>, 0.008);
mods.exnihilocreatio.Sieve.addIronMeshRecipe(<ore:gravel>, <astralsorcery:itemcraftingcomponent:0>, 0.008);
mods.exnihilocreatio.Sieve.addIronMeshRecipe(<ore:gravel>, <abyssalcraft:coralium>, 0.008);
mods.exnihilocreatio.Sieve.addIronMeshRecipe(<ore:gravel>, <rftools:dimensional_shard>, 0.008);
mods.exnihilocreatio.Sieve.addIronMeshRecipe(<ore:gravel>, <quark:biotite>, 0.008);
mods.exnihilocreatio.Sieve.addIronMeshRecipe(<ore:gravel>, <biomesoplenty:gem:1>, 0.008);
mods.exnihilocreatio.Sieve.addIronMeshRecipe(<ore:gravel>, <biomesoplenty:gem:6>, 0.008);
mods.exnihilocreatio.Sieve.addIronMeshRecipe(<ore:gravel>, <biomesoplenty:gem:4>, 0.008);
mods.exnihilocreatio.Sieve.addIronMeshRecipe(<ore:gravel>, <biomesoplenty:gem:3>, 0.008);
mods.exnihilocreatio.Sieve.addDiamondMeshRecipe(<ore:gravel>, <minecraft:diamond>, 0.016);
mods.exnihilocreatio.Sieve.addDiamondMeshRecipe(<ore:gravel>, <minecraft:emerald>, 0.016);
mods.exnihilocreatio.Sieve.addDiamondMeshRecipe(<ore:gravel>, <exnihilocreatio:item_ore_gold:0>, 0.15);
mods.exnihilocreatio.Sieve.addDiamondMeshRecipe(<ore:gravel>, <exnihilocreatio:item_ore_iron:0>, 0.25);
mods.exnihilocreatio.Sieve.addDiamondMeshRecipe(<ore:gravel>, <exnihilocreatio:item_ore_copper:0>, 0.25);
mods.exnihilocreatio.Sieve.addDiamondMeshRecipe(<ore:gravel>, <exnihilocreatio:item_ore_lead:0>, 0.15);
mods.exnihilocreatio.Sieve.addDiamondMeshRecipe(<ore:gravel>, <exnihilocreatio:item_ore_nickel:0>, 0.15);
mods.exnihilocreatio.Sieve.addDiamondMeshRecipe(<ore:gravel>, <exnihilocreatio:item_ore_tungsten:0>, 0.15);
mods.exnihilocreatio.Sieve.addDiamondMeshRecipe(<ore:gravel>, <exnihilocreatio:item_ore_uranium:0>, 0.1);
mods.exnihilocreatio.Sieve.addDiamondMeshRecipe(<ore:gravel>, <exnihilocreatio:item_ore_osmium:0>, 0.1);
mods.exnihilocreatio.Sieve.addDiamondMeshRecipe(<ore:gravel>, <exnihilocreatio:item_ore_platinum:0>, 0.12);
mods.exnihilocreatio.Sieve.addDiamondMeshRecipe(<ore:gravel>, <exnihilocreatio:item_ore_boron>, 0.1);
mods.exnihilocreatio.Sieve.addDiamondMeshRecipe(<ore:gravel>, <exnihilocreatio:item_ore_lithium>, 0.1);
mods.exnihilocreatio.Sieve.addDiamondMeshRecipe(<ore:gravel>, <exnihilocreatio:item_ore_magnesium>, 0.1);
mods.exnihilocreatio.Sieve.addDiamondMeshRecipe(<ore:gravel>, <exnihilocreatio:item_ore_mithril>, 0.1);
mods.exnihilocreatio.Sieve.addDiamondMeshRecipe(<ore:gravel>, <exnihilocreatio:item_ore_thorium>, 0.1);
mods.exnihilocreatio.Sieve.addDiamondMeshRecipe(<ore:gravel>, <exnihilocreatio:item_ore_titanium>, 0.1);
mods.exnihilocreatio.Sieve.addDiamondMeshRecipe(<ore:gravel>, <exnihilocreatio:item_ore_yellorium>, 0.1);
mods.exnihilocreatio.Sieve.addDiamondMeshRecipe(<ore:gravel>, <silentgems:gemshard:12>, 0.016);
mods.exnihilocreatio.Sieve.addDiamondMeshRecipe(<ore:gravel>, <thaumcraft:amber>, 0.016);
mods.exnihilocreatio.Sieve.addDiamondMeshRecipe(<ore:gravel>, <biomesoplenty:gem:0>, 0.016);
mods.exnihilocreatio.Sieve.addDiamondMeshRecipe(<ore:gravel>, <forestry:apatite>, 0.016);
mods.exnihilocreatio.Sieve.addDiamondMeshRecipe(<ore:gravel>, <astralsorcery:itemcraftingcomponent:0>, 0.016);
mods.exnihilocreatio.Sieve.addDiamondMeshRecipe(<ore:gravel>, <silentgems:gemshard:6>, 0.016);
mods.exnihilocreatio.Sieve.addDiamondMeshRecipe(<ore:gravel>, <silentgems:craftingmaterial:3>, 0.016);
mods.exnihilocreatio.Sieve.addDiamondMeshRecipe(<ore:gravel>, <abyssalcraft:coralium>, 0.016);
mods.exnihilocreatio.Sieve.addDiamondMeshRecipe(<ore:gravel>, <rftools:dimensional_shard>, 0.016);
mods.exnihilocreatio.Sieve.addDiamondMeshRecipe(<ore:gravel>, <quark:biotite>, 0.016);
mods.exnihilocreatio.Sieve.addDiamondMeshRecipe(<ore:gravel>, <silentgems:gemshard:1>, 0.016);
mods.exnihilocreatio.Sieve.addDiamondMeshRecipe(<ore:gravel>, <silentgems:gemshard:4>, 0.016);
mods.exnihilocreatio.Sieve.addDiamondMeshRecipe(<ore:gravel>, <silentgems:gemshard:7>, 0.016);
mods.exnihilocreatio.Sieve.addDiamondMeshRecipe(<ore:gravel>, <silentgems:gemshard:10>, 0.016);
mods.exnihilocreatio.Sieve.addDiamondMeshRecipe(<ore:gravel>, <silentgems:gemshard:13>, 0.016);
mods.exnihilocreatio.Sieve.addDiamondMeshRecipe(<ore:gravel>, <silentgems:gemshard:14>, 0.016);
mods.exnihilocreatio.Sieve.addDiamondMeshRecipe(<ore:gravel>, <silentgems:gemshard:15>, 0.016);
mods.exnihilocreatio.Sieve.addDiamondMeshRecipe(<ore:gravel>, <biomesoplenty:gem:1>, 0.016);
mods.exnihilocreatio.Sieve.addDiamondMeshRecipe(<ore:gravel>, <biomesoplenty:gem:6>, 0.016);
mods.exnihilocreatio.Sieve.addDiamondMeshRecipe(<ore:gravel>, <biomesoplenty:gem:4>, 0.016);
mods.exnihilocreatio.Sieve.addDiamondMeshRecipe(<ore:gravel>, <biomesoplenty:gem:3>, 0.016);
mods.exnihilocreatio.Sieve.addDiamondMeshRecipe(<ore:gravel>, <silentgems:gemshard:5>, 0.016);
//Sand
mods.exnihilocreatio.Sieve.addStringMeshRecipe(<ore:sand>, <minecraft:dye:3>, 0.03);
mods.exnihilocreatio.Sieve.addStringMeshRecipe(<ore:sand>, <forestry:apatite>, 0.01);
mods.exnihilocreatio.Sieve.addFlintMeshRecipe(<ore:sand>, <exnihilocreatio:item_ore_aluminium:0>, 0.05);
mods.exnihilocreatio.Sieve.addFlintMeshRecipe(<ore:sand>, <exnihilocreatio:item_ore_tin:0>, 0.05);
mods.exnihilocreatio.Sieve.addFlintMeshRecipe(<ore:sand>, <forestry:apatite>, 0.02);
mods.exnihilocreatio.Sieve.addIronMeshRecipe(<ore:sand>, <exnihilocreatio:item_ore_aluminium:0>, 0.10);
mods.exnihilocreatio.Sieve.addIronMeshRecipe(<ore:sand>, <exnihilocreatio:item_ore_tin:0>, 0.10);
mods.exnihilocreatio.Sieve.addIronMeshRecipe(<ore:sand>, <actuallyadditions:item_misc:5>, 0.02);
mods.exnihilocreatio.Sieve.addIronMeshRecipe(<ore:sand>, <forestry:apatite>, 0.03);
mods.exnihilocreatio.Sieve.addDiamondMeshRecipe(<ore:sand>, <minecraft:prismarine_shard>, 0.02);
mods.exnihilocreatio.Sieve.addDiamondMeshRecipe(<ore:sand>, <exnihilocreatio:item_ore_aluminium:0>, 0.25);
mods.exnihilocreatio.Sieve.addDiamondMeshRecipe(<ore:sand>, <exnihilocreatio:item_ore_silver:0>, 0.15);
mods.exnihilocreatio.Sieve.addDiamondMeshRecipe(<ore:sand>, <exnihilocreatio:item_ore_tin:0>, 0.25);
mods.exnihilocreatio.Sieve.addDiamondMeshRecipe(<ore:sand>, <actuallyadditions:item_misc:5>, 0.05);
mods.exnihilocreatio.Sieve.addDiamondMeshRecipe(<ore:sand>, <forestry:apatite>, 0.05);
//Dust
mods.exnihilocreatio.Sieve.addFlintMeshRecipe(<ore:dust>, <minecraft:dye:15>, 0.20);
mods.exnihilocreatio.Sieve.addFlintMeshRecipe(<ore:dust>, <minecraft:gunpowder>, 0.07);
mods.exnihilocreatio.Sieve.addIronMeshRecipe(<ore:dust>, <minecraft:redstone>, 0.125);
mods.exnihilocreatio.Sieve.addIronMeshRecipe(<ore:dust>, <minecraft:glowstone_dust>, 0.0625);
mods.exnihilocreatio.Sieve.addIronMeshRecipe(<ore:dust>, <minecraft:blaze_powder>, 0.05);
mods.exnihilocreatio.Sieve.addIronMeshRecipe(<ore:dust>, <techreborn:dust:5>, 0.0625);
mods.exnihilocreatio.Sieve.addIronMeshRecipe(<ore:dust>, <techreborn:dust:11>, 0.0625);
mods.exnihilocreatio.Sieve.addIronMeshRecipe(<ore:dust>, <libvulpes:productdust:0>, 0.0625);
mods.exnihilocreatio.Sieve.addIronMeshRecipe(<ore:dust>, <techreborn:dust:23>, 0.0625);
mods.exnihilocreatio.Sieve.addIronMeshRecipe(<ore:dust>, <abyssalcraft:nitre>, 0.0625);
mods.exnihilocreatio.Sieve.addIronMeshRecipe(<ore:dust>, <techreborn:dust:39>, 0.0625);
mods.exnihilocreatio.Sieve.addIronMeshRecipe(<ore:dust>, <techreborn:dust:50>, 0.0625);
mods.exnihilocreatio.Sieve.addIronMeshRecipe(<ore:dust>, <thebetweenlands:items_misc:18>, 0.0625);
mods.exnihilocreatio.Sieve.addDiamondMeshRecipe(<ore:dust>, <minecraft:redstone>, 0.25);
mods.exnihilocreatio.Sieve.addDiamondMeshRecipe(<ore:dust>, <enderio:item_material:20>, 0.01);
mods.exnihilocreatio.Sieve.addDiamondMeshRecipe(<ore:dust>, <appliedenergistics2:material:45>, 0.3);
mods.exnihilocreatio.Sieve.addDiamondMeshRecipe(<ore:dust>, <techreborn:dust:5>, 0.125);
mods.exnihilocreatio.Sieve.addDiamondMeshRecipe(<ore:dust>, <techreborn:dust:11>, 0.125);
mods.exnihilocreatio.Sieve.addDiamondMeshRecipe(<ore:dust>, <libvulpes:productdust:0>, 0.125);
mods.exnihilocreatio.Sieve.addDiamondMeshRecipe(<ore:dust>, <techreborn:dust:23>, 0.125);
mods.exnihilocreatio.Sieve.addDiamondMeshRecipe(<ore:dust>, <abyssalcraft:nitre>, 0.125);
mods.exnihilocreatio.Sieve.addDiamondMeshRecipe(<ore:dust>, <techreborn:dust:39>, 0.125);
mods.exnihilocreatio.Sieve.addDiamondMeshRecipe(<ore:dust>, <techreborn:dust:50>, 0.125);
mods.exnihilocreatio.Sieve.addDiamondMeshRecipe(<ore:dust>, <thebetweenlands:items_misc:18>, 0.125);
//Crushed Netherrack
mods.exnihilocreatio.Sieve.addFlintMeshRecipe(<exnihilocreatio:block_netherrack_crushed:0>, <exnihilocreatio:item_ore_gold:0>, 0.25);
mods.exnihilocreatio.Sieve.addFlintMeshRecipe(<exnihilocreatio:block_netherrack_crushed:0>, <exnihilocreatio:item_ore_ardite:0>, 0.1);
mods.exnihilocreatio.Sieve.addFlintMeshRecipe(<exnihilocreatio:block_netherrack_crushed:0>, <exnihilocreatio:item_ore_cobalt:0>, 0.1);
//Soul Sand
mods.exnihilocreatio.Sieve.addDiamondMeshRecipe(<minecraft:soul_sand:0>, <minecraft:nether_wart>, 0.1);
mods.exnihilocreatio.Sieve.addDiamondMeshRecipe(<minecraft:soul_sand:0>, <minecraft:ghast_tear>, 0.02);
mods.exnihilocreatio.Sieve.addDiamondMeshRecipe(<minecraft:soul_sand:0>, <minecraft:quartz>, 1.0);
mods.exnihilocreatio.Sieve.addDiamondMeshRecipe(<minecraft:soul_sand:0>, <minecraft:quartz>, 0.8);
//Crushed Skystone
mods.exnihilocreatio.Sieve.addDiamondMeshRecipe(<exnihilocreatio:block_skystone_crushed:0>, <appliedenergistics2:material:0>, 0.02);
mods.exnihilocreatio.Sieve.addDiamondMeshRecipe(<exnihilocreatio:block_skystone_crushed:0>, <appliedenergistics2:crystal_seed>.withTag({progress: 0.0 as float}), 0.02);
mods.exnihilocreatio.Sieve.addDiamondMeshRecipe(<exnihilocreatio:block_skystone_crushed:0>, <appliedenergistics2:material:1>, 0.001);
//Crushed End Stone
mods.exnihilocreatio.Sieve.addIronMeshRecipe(<exnihilocreatio:block_endstone_crushed:0>, <exnihilocreatio:item_ore_aluminium:0>, 0.15);
mods.exnihilocreatio.Sieve.addIronMeshRecipe(<exnihilocreatio:block_endstone_crushed:0>, <exnihilocreatio:item_ore_silver:0>, 0.15);
mods.exnihilocreatio.Sieve.addDiamondMeshRecipe(<exnihilocreatio:block_endstone_crushed:0>, <exnihilocreatio:item_ore_aluminium:0>, 0.25);
mods.exnihilocreatio.Sieve.addDiamondMeshRecipe(<exnihilocreatio:block_endstone_crushed:0>, <exnihilocreatio:item_ore_silver:0>, 0.25);
mods.exnihilocreatio.Sieve.addDiamondMeshRecipe(<exnihilocreatio:block_endstone_crushed:0>, <draconicevolution:draconium_dust>, 0.08);
mods.exnihilocreatio.Sieve.addDiamondMeshRecipe(<exnihilocreatio:block_endstone_crushed:0>, <silentgems:gemshard:32>, 0.016);
mods.exnihilocreatio.Sieve.addDiamondMeshRecipe(<exnihilocreatio:block_endstone_crushed:0>, <silentgems:gemshard:33>, 0.016);
mods.exnihilocreatio.Sieve.addDiamondMeshRecipe(<exnihilocreatio:block_endstone_crushed:0>, <silentgems:gemshard:34>, 0.016);
mods.exnihilocreatio.Sieve.addDiamondMeshRecipe(<exnihilocreatio:block_endstone_crushed:0>, <silentgems:gemshard:35>, 0.016);
mods.exnihilocreatio.Sieve.addDiamondMeshRecipe(<exnihilocreatio:block_endstone_crushed:0>, <silentgems:gemshard:36>, 0.016);
mods.exnihilocreatio.Sieve.addDiamondMeshRecipe(<exnihilocreatio:block_endstone_crushed:0>, <silentgems:gemshard:37>, 0.016);
mods.exnihilocreatio.Sieve.addDiamondMeshRecipe(<exnihilocreatio:block_endstone_crushed:0>, <silentgems:gemshard:38>, 0.016);
mods.exnihilocreatio.Sieve.addDiamondMeshRecipe(<exnihilocreatio:block_endstone_crushed:0>, <silentgems:gemshard:39>, 0.016);
mods.exnihilocreatio.Sieve.addDiamondMeshRecipe(<exnihilocreatio:block_endstone_crushed:0>, <silentgems:gemshard:40>, 0.016);
mods.exnihilocreatio.Sieve.addDiamondMeshRecipe(<exnihilocreatio:block_endstone_crushed:0>, <silentgems:gemshard:41>, 0.016);
mods.exnihilocreatio.Sieve.addDiamondMeshRecipe(<exnihilocreatio:block_endstone_crushed:0>, <silentgems:gemshard:42>, 0.016);
mods.exnihilocreatio.Sieve.addDiamondMeshRecipe(<exnihilocreatio:block_endstone_crushed:0>, <silentgems:gemshard:43>, 0.016);
mods.exnihilocreatio.Sieve.addDiamondMeshRecipe(<exnihilocreatio:block_endstone_crushed:0>, <silentgems:gemshard:44>, 0.016);
mods.exnihilocreatio.Sieve.addDiamondMeshRecipe(<exnihilocreatio:block_endstone_crushed:0>, <silentgems:gemshard:45>, 0.016);
mods.exnihilocreatio.Sieve.addDiamondMeshRecipe(<exnihilocreatio:block_endstone_crushed:0>, <silentgems:gemshard:46>, 0.016);
mods.exnihilocreatio.Sieve.addDiamondMeshRecipe(<exnihilocreatio:block_endstone_crushed:0>, <silentgems:gemshard:47>, 0.016);
mods.exnihilocreatio.Sieve.addDiamondMeshRecipe(<exnihilocreatio:block_endstone_crushed:0>, <minecraft:chorus_fruit>, 0.10);
mods.exnihilocreatio.Sieve.addDiamondMeshRecipe(<exnihilocreatio:block_endstone_crushed:0>, <silentgems:craftingmaterial:5>, 0.016);
//Crished Netherrack
mods.exnihilocreatio.Sieve.addIronMeshRecipe(<exnihilocreatio:block_netherrack_crushed:0>, <exnihilocreatio:item_ore_gold:0>, 0.25);
mods.exnihilocreatio.Sieve.addIronMeshRecipe(<exnihilocreatio:block_netherrack_crushed:0>, <exnihilocreatio:item_ore_ardite:0>, 0.2);
mods.exnihilocreatio.Sieve.addIronMeshRecipe(<exnihilocreatio:block_netherrack_crushed:0>, <exnihilocreatio:item_ore_cobalt:0>, 0.2);
mods.exnihilocreatio.Sieve.addIronMeshRecipe(<exnihilocreatio:block_netherrack_crushed:0>, <minecraft:blaze_powder>, 0.05);
mods.exnihilocreatio.Sieve.addDiamondMeshRecipe(<exnihilocreatio:block_netherrack_crushed:0>, <exnihilocreatio:item_ore_gold:0>, 0.4);
mods.exnihilocreatio.Sieve.addDiamondMeshRecipe(<exnihilocreatio:block_netherrack_crushed:0>, <exnihilocreatio:item_ore_ardite:0>, 0.3);
mods.exnihilocreatio.Sieve.addDiamondMeshRecipe(<exnihilocreatio:block_netherrack_crushed:0>, <exnihilocreatio:item_ore_cobalt:0>, 0.3);
mods.exnihilocreatio.Sieve.addDiamondMeshRecipe(<exnihilocreatio:block_netherrack_crushed:0>, <silentgems:gemshard:16>, 0.016);
mods.exnihilocreatio.Sieve.addDiamondMeshRecipe(<exnihilocreatio:block_netherrack_crushed:0>, <silentgems:gemshard:17>, 0.016);
mods.exnihilocreatio.Sieve.addDiamondMeshRecipe(<exnihilocreatio:block_netherrack_crushed:0>, <silentgems:gemshard:18>, 0.016);
mods.exnihilocreatio.Sieve.addDiamondMeshRecipe(<exnihilocreatio:block_netherrack_crushed:0>, <silentgems:gemshard:19>, 0.016);
mods.exnihilocreatio.Sieve.addDiamondMeshRecipe(<exnihilocreatio:block_netherrack_crushed:0>, <silentgems:gemshard:20>, 0.016);
mods.exnihilocreatio.Sieve.addDiamondMeshRecipe(<exnihilocreatio:block_netherrack_crushed:0>, <silentgems:gemshard:21>, 0.016);
mods.exnihilocreatio.Sieve.addDiamondMeshRecipe(<exnihilocreatio:block_netherrack_crushed:0>, <silentgems:gemshard:22>, 0.016);
mods.exnihilocreatio.Sieve.addDiamondMeshRecipe(<exnihilocreatio:block_netherrack_crushed:0>, <silentgems:gemshard:23>, 0.016);
mods.exnihilocreatio.Sieve.addDiamondMeshRecipe(<exnihilocreatio:block_netherrack_crushed:0>, <silentgems:gemshard:24>, 0.016);
mods.exnihilocreatio.Sieve.addDiamondMeshRecipe(<exnihilocreatio:block_netherrack_crushed:0>, <silentgems:gemshard:25>, 0.016);
mods.exnihilocreatio.Sieve.addDiamondMeshRecipe(<exnihilocreatio:block_netherrack_crushed:0>, <silentgems:gemshard:26>, 0.016);
mods.exnihilocreatio.Sieve.addDiamondMeshRecipe(<exnihilocreatio:block_netherrack_crushed:0>, <silentgems:gemshard:27>, 0.016);
mods.exnihilocreatio.Sieve.addDiamondMeshRecipe(<exnihilocreatio:block_netherrack_crushed:0>, <silentgems:gemshard:28>, 0.016);
mods.exnihilocreatio.Sieve.addDiamondMeshRecipe(<exnihilocreatio:block_netherrack_crushed:0>, <silentgems:gemshard:29>, 0.016);
mods.exnihilocreatio.Sieve.addDiamondMeshRecipe(<exnihilocreatio:block_netherrack_crushed:0>, <silentgems:gemshard:30>, 0.016);
mods.exnihilocreatio.Sieve.addDiamondMeshRecipe(<exnihilocreatio:block_netherrack_crushed:0>, <silentgems:gemshard:31>, 0.016);
//Silt (Betweenland)
mods.exnihilocreatio.Sieve.addIronMeshRecipe(<thebetweenlands:silt>, <jaopca:exnihilocreatio_piece.syrmorite>, 0.1);
mods.exnihilocreatio.Sieve.addDiamondMeshRecipe(<thebetweenlands:silt>, <jaopca:exnihilocreatio_piece.syrmorite>, 0.25);
mods.exnihilocreatio.Sieve.addDiamondMeshRecipe(<thebetweenlands:silt>, <jaopca:exnihilocreatio_piece.octine>, 0.1);
//AbyssalSand
mods.exnihilocreatio.Sieve.addDiamondMeshRecipe(<abyssalcraft:abyssalsand>, <jaopca:exnihilocreatio_piece.liquified_coralium>, 0.1);
mods.exnihilocreatio.Sieve.addDiamondMeshRecipe(<abyssalcraft:abyssalsand>, <jaopca:exnihilocreatio_piece.abyssalnite>, 0.15);

//Remove
mods.jei.JEI.removeAndHide(<jaopca:exnihilocreatio_piece.mithril>);
mods.jei.JEI.removeAndHide(<jaopca:exnihilocreatio_piece.iridium>);
mods.jei.JEI.removeAndHide(<jaopca:exnihilocreatio_piece.astral_starmetal>);
mods.jei.JEI.removeAndHide(<jaopca:exnihilocreatio_chunk.astral_starmetal>);
mods.jei.JEI.removeAndHide(<jaopca:exnihilocreatio_chunk.mithril>);
mods.jei.JEI.removeAndHide(<jaopca:exnihilocreatio_chunk.iridium>);

print("--- exnihilo.zs initialized ---");